<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Aevalsistant.Tests</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aevalsistant.csproj" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
